### ISSUE TITLE
Website is down, FAQ link also dead

### ISSUE THREAD

**Issue by wohali** [atomicptr/LoginWars2#18]
I actually get a DNS lookup failure on loginwars2.kasoki.de.

Your FAQ links to http://kasoki.github.io/LoginWars2 which fails because this repo doesn't have GH pages set up, either.

**Comment by atomicptr** [comment]
Yep, I removed my old domain and forgot to add a subdomain to the new one. It's online now via http://loginwars2.qr9.de thanks for the note!
