### ISSUE TITLE
Add tutorial

### ISSUE THREAD

**Issue by atomicptr** [atomicptr/LoginWars2#3]
After some user testing I realized that editing accounts doesn't seem to be as easy to understand as I hoped it would be so I want to add a tutorial which guides the user through the first time. Maybe changing the UX would be a better idea but I'm still not sure if I know a better way to do this.

**Comment by kasoki** [comment]
Move to later version, I'll add a basic tutorial to the FAQ for now.

**Comment by kasoki** [comment]
Would be interesting to see if this is still needed.

**Comment by atomicptr** [comment]
Closed since it's probably not needed anymore
